# Generated by Django 5.0.3 on 2024-03-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_birth',
            new_name='date_of_birth',
        ),
    ]
